# config.yml
monte_carlo:
  iterations: 2
  std_dev: 0.5
  log_filename: 'alumet_execution.log'

dem: 'DEM.gz'


model: 
  debug: true
  visualize: false

  rainfall:
    on: false
    mask: 'rain_mask.gz'
    source: 'rain_source.csv'

  landcover:
    on: false
    mask: 'landcover.gz'

  initial_conditions:
    h0: 0.0 # initial water height
  boundary_conditions:
    box_upstream: # X and Y coordinates of the upstream box
      - [1427, 195]
      - [1446, 243]
    box_downstream: # X and Y coordinates of the downstream box
      - [58, 1645]
      - [72, 1170]
    discharge_values: # time series of discharge values for the upstream [time, flow rate]
      - [0, 1000]
      - [3600, 100]
    downstream_h: # time series of water height values for the downstream [time, height]
      - [0, 5]
      - [3600, 5]

  friction: # friction values and indexes. Uses default if landcover is not used.
    default: 0.035
    landcover: 
      friction: [0.035, 0.055]
      value: [0, 1]

  solver:
    start_time: 0
    end_time: 3600
    log_interval: 600
    save_interval: 1200 

  observation:
    gauges_position:
    - [560, 1030]
    - [1140, 330]



